// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protobuf/api/user/message.proto

package user

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age           int32                  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_protobuf_api_user_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_api_user_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_api_user_message_proto_rawDescGZIP(), []int{0}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type CreateUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Greeting      string                 `protobuf:"bytes,1,opt,name=greeting,proto3" json:"greeting,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_protobuf_api_user_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_api_user_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_api_user_message_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserResponse) GetGreeting() string {
	if x != nil {
		return x.Greeting
	}
	return ""
}

var File_protobuf_api_user_message_proto protoreflect.FileDescriptor

const file_protobuf_api_user_message_proto_rawDesc = "" +
	"\n" +
	"\x1fprotobuf/api/user/message.proto\x12\bapi.user\x1a\x1fgoogle/api/field_behavior.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a\x17validate/validate.proto\"\xef\x02\n" +
	"\x11CreateUserRequest\x12l\n" +
	"\x04name\x18\x01 \x01(\tBX\x92AI*\x04name2\x10name of the userJ\a\"Denis\"\x8a\x01\x15^[a-zA-Z0-9]{1, 512}$\xd2\x01\x04true\xa2\x02\x06string\xe0A\x02\xfaB\x06r\x04\x10\x01\x18\x14R\x04name\x12Y\n" +
	"\x03age\x18\x02 \x01(\x05BG\x92A7*\x03age2\x0fage of the userJ\x03123\x8a\x01\a^[0-9]$\xd2\x01\x05false\xa2\x02\ainteger\xe0A\x01\xfaB\a\x1a\x05\x18\x96\x01(\x01R\x03age:\x90\x01\x92A\x8c\x01\n" +
	"+*\x11CreateUserRequest2\x0fCreate new user\xd2\x01\x04name*?\n" +
	"\rFind out more\x12.https://github.com/grpc-ecosystem/grpc-gateway2\x1c{\"name\": \"Denis\", \"age\": 30}\"\xd1\x02\n" +
	"\x12CreateUserResponse\x12\x80\x01\n" +
	"\bgreeting\x18\x01 \x01(\tBd\x92A^*\bgreeting2\x14greeting of the userJ\x14\"User Denis created\"\x8a\x01\x15^[a-zA-Z0-9]{1, 512}$\xd2\x01\x04true\xa2\x02\x06string\xe0A\x02R\bgreeting:\xb7\x01\x92A\xb3\x01\n" +
	"<*\x12CreateUserResponse2\x1bCreateUser response message\xd2\x01\bgreeting*V\n" +
	"$Find out more about ABitOfEverything\x12.https://github.com/grpc-ecosystem/grpc-gateway2\x1b{\"result_message\": \"hello\"}B\x1bZ\x19my_grpc/pkg/api/user;userb\x06proto3"

var (
	file_protobuf_api_user_message_proto_rawDescOnce sync.Once
	file_protobuf_api_user_message_proto_rawDescData []byte
)

func file_protobuf_api_user_message_proto_rawDescGZIP() []byte {
	file_protobuf_api_user_message_proto_rawDescOnce.Do(func() {
		file_protobuf_api_user_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_api_user_message_proto_rawDesc), len(file_protobuf_api_user_message_proto_rawDesc)))
	})
	return file_protobuf_api_user_message_proto_rawDescData
}

var file_protobuf_api_user_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_api_user_message_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: api.user.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: api.user.CreateUserResponse
}
var file_protobuf_api_user_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_api_user_message_proto_init() }
func file_protobuf_api_user_message_proto_init() {
	if File_protobuf_api_user_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_api_user_message_proto_rawDesc), len(file_protobuf_api_user_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_api_user_message_proto_goTypes,
		DependencyIndexes: file_protobuf_api_user_message_proto_depIdxs,
		MessageInfos:      file_protobuf_api_user_message_proto_msgTypes,
	}.Build()
	File_protobuf_api_user_message_proto = out.File
	file_protobuf_api_user_message_proto_goTypes = nil
	file_protobuf_api_user_message_proto_depIdxs = nil
}
