// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protobuf/api/user/service.proto

package user

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_protobuf_api_user_service_proto protoreflect.FileDescriptor

const file_protobuf_api_user_service_proto_rawDesc = "" +
	"\n" +
	"\x1fprotobuf/api/user/service.proto\x12\bapi.user\x1a\x1fprotobuf/api/user/message.proto\x1a\x1cgoogle/api/annotations.proto\x1a.protoc-gen-openapiv2/options/annotations.proto2\xec\x01\n" +
	"\vUserService\x12\x7f\n" +
	"\n" +
	"CreateUser\x12\x1b.api.user.CreateUserRequest\x1a\x1c.api.user.CreateUserResponse\"6\x92A \n" +
	"\x04user\x12\n" +
	"CreateUser\x1a\fCreate new u\x82\xd3\xe4\x93\x02\r:\x01*\"\b/v1/user\x1a\\\x92AY\n" +
	"\vUserService\x12)Наш крутой REST API сервис\x1a\x1f\n" +
	"\x1dБольше примеровB\x91\x02\x92A\xf2\x01\x12\x83\x01\n" +
	"\x0eLet's Go gRPC!\x12\rLearning gRPC\"\x16\n" +
	"\aDenis Z\x1a\vd@gmail.com*C\n" +
	"\x14BSD 3-Clause License\x12+https://opensource.org/license/bsd-3-clause2\x050.1.0*\x02\x01\x022\x10application/json:\x10application/jsonj!\n" +
	"\vUserService\x12\x12first gRPC servicer\x1f\n" +
	"\x1dБольше примеровZ\x19my_grpc/pkg/api/user;userb\x06proto3"

var file_protobuf_api_user_service_proto_goTypes = []any{
	(*CreateUserRequest)(nil),  // 0: api.user.CreateUserRequest
	(*CreateUserResponse)(nil), // 1: api.user.CreateUserResponse
}
var file_protobuf_api_user_service_proto_depIdxs = []int32{
	0, // 0: api.user.UserService.CreateUser:input_type -> api.user.CreateUserRequest
	1, // 1: api.user.UserService.CreateUser:output_type -> api.user.CreateUserResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_api_user_service_proto_init() }
func file_protobuf_api_user_service_proto_init() {
	if File_protobuf_api_user_service_proto != nil {
		return
	}
	file_protobuf_api_user_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_api_user_service_proto_rawDesc), len(file_protobuf_api_user_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_api_user_service_proto_goTypes,
		DependencyIndexes: file_protobuf_api_user_service_proto_depIdxs,
	}.Build()
	File_protobuf_api_user_service_proto = out.File
	file_protobuf_api_user_service_proto_goTypes = nil
	file_protobuf_api_user_service_proto_depIdxs = nil
}
