// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: protobuf/api/salary/messages.proto

package salary

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on GetSalaryRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSalaryRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSalaryRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSalaryRequestMultiError, or nil if none found.
func (m *GetSalaryRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSalaryRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for NameEmployee

	// no validation rules for Hours

	if len(errors) > 0 {
		return GetSalaryRequestMultiError(errors)
	}

	return nil
}

// GetSalaryRequestMultiError is an error wrapping multiple validation errors
// returned by GetSalaryRequest.ValidateAll() if the designated constraints
// aren't met.
type GetSalaryRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSalaryRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSalaryRequestMultiError) AllErrors() []error { return m }

// GetSalaryRequestValidationError is the validation error returned by
// GetSalaryRequest.Validate if the designated constraints aren't met.
type GetSalaryRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSalaryRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSalaryRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSalaryRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSalaryRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSalaryRequestValidationError) ErrorName() string { return "GetSalaryRequestValidationError" }

// Error satisfies the builtin error interface
func (e GetSalaryRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSalaryRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSalaryRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSalaryRequestValidationError{}

// Validate checks the field values on GetSalaryResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *GetSalaryResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetSalaryResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetSalaryResponseMultiError, or nil if none found.
func (m *GetSalaryResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetSalaryResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Salary

	// no validation rules for Name

	if len(errors) > 0 {
		return GetSalaryResponseMultiError(errors)
	}

	return nil
}

// GetSalaryResponseMultiError is an error wrapping multiple validation errors
// returned by GetSalaryResponse.ValidateAll() if the designated constraints
// aren't met.
type GetSalaryResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetSalaryResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetSalaryResponseMultiError) AllErrors() []error { return m }

// GetSalaryResponseValidationError is the validation error returned by
// GetSalaryResponse.Validate if the designated constraints aren't met.
type GetSalaryResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetSalaryResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetSalaryResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetSalaryResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetSalaryResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetSalaryResponseValidationError) ErrorName() string {
	return "GetSalaryResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetSalaryResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetSalaryResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetSalaryResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetSalaryResponseValidationError{}
