// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protobuf/api/salary/messages.proto

package salary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSalaryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NameEmployee  string                 `protobuf:"bytes,1,opt,name=nameEmployee,proto3" json:"nameEmployee,omitempty"`
	Hours         int32                  `protobuf:"varint,2,opt,name=hours,proto3" json:"hours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalaryRequest) Reset() {
	*x = GetSalaryRequest{}
	mi := &file_protobuf_api_salary_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalaryRequest) ProtoMessage() {}

func (x *GetSalaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_api_salary_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalaryRequest.ProtoReflect.Descriptor instead.
func (*GetSalaryRequest) Descriptor() ([]byte, []int) {
	return file_protobuf_api_salary_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetSalaryRequest) GetNameEmployee() string {
	if x != nil {
		return x.NameEmployee
	}
	return ""
}

func (x *GetSalaryRequest) GetHours() int32 {
	if x != nil {
		return x.Hours
	}
	return 0
}

type GetSalaryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salary        int32                  `protobuf:"varint,1,opt,name=salary,proto3" json:"salary,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSalaryResponse) Reset() {
	*x = GetSalaryResponse{}
	mi := &file_protobuf_api_salary_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSalaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSalaryResponse) ProtoMessage() {}

func (x *GetSalaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_api_salary_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSalaryResponse.ProtoReflect.Descriptor instead.
func (*GetSalaryResponse) Descriptor() ([]byte, []int) {
	return file_protobuf_api_salary_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetSalaryResponse) GetSalary() int32 {
	if x != nil {
		return x.Salary
	}
	return 0
}

func (x *GetSalaryResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_protobuf_api_salary_messages_proto protoreflect.FileDescriptor

const file_protobuf_api_salary_messages_proto_rawDesc = "" +
	"\n" +
	"\"protobuf/api/salary/messages.proto\x12\n" +
	"api.salary\"L\n" +
	"\x10GetSalaryRequest\x12\"\n" +
	"\fnameEmployee\x18\x01 \x01(\tR\fnameEmployee\x12\x14\n" +
	"\x05hours\x18\x02 \x01(\x05R\x05hours\"?\n" +
	"\x11GetSalaryResponse\x12\x16\n" +
	"\x06salary\x18\x01 \x01(\x05R\x06salary\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04nameB(Z&my_grpc/pkg/protobuf/api/salary;salaryb\x06proto3"

var (
	file_protobuf_api_salary_messages_proto_rawDescOnce sync.Once
	file_protobuf_api_salary_messages_proto_rawDescData []byte
)

func file_protobuf_api_salary_messages_proto_rawDescGZIP() []byte {
	file_protobuf_api_salary_messages_proto_rawDescOnce.Do(func() {
		file_protobuf_api_salary_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobuf_api_salary_messages_proto_rawDesc), len(file_protobuf_api_salary_messages_proto_rawDesc)))
	})
	return file_protobuf_api_salary_messages_proto_rawDescData
}

var file_protobuf_api_salary_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_api_salary_messages_proto_goTypes = []any{
	(*GetSalaryRequest)(nil),  // 0: api.salary.GetSalaryRequest
	(*GetSalaryResponse)(nil), // 1: api.salary.GetSalaryResponse
}
var file_protobuf_api_salary_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_api_salary_messages_proto_init() }
func file_protobuf_api_salary_messages_proto_init() {
	if File_protobuf_api_salary_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_api_salary_messages_proto_rawDesc), len(file_protobuf_api_salary_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_api_salary_messages_proto_goTypes,
		DependencyIndexes: file_protobuf_api_salary_messages_proto_depIdxs,
		MessageInfos:      file_protobuf_api_salary_messages_proto_msgTypes,
	}.Build()
	File_protobuf_api_salary_messages_proto = out.File
	file_protobuf_api_salary_messages_proto_goTypes = nil
	file_protobuf_api_salary_messages_proto_depIdxs = nil
}
