// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protobuf/api/salary/service.proto

package salary

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_protobuf_api_salary_service_proto protoreflect.FileDescriptor

const file_protobuf_api_salary_service_proto_rawDesc = "" +
	"\n" +
	"!protobuf/api/salary/service.proto\x12\n" +
	"api.salary\x1a\"protobuf/api/salary/messages.proto2Y\n" +
	"\rSalaryService\x12H\n" +
	"\tGetSalary\x12\x1c.api.salary.GetSalaryRequest\x1a\x1d.api.salary.GetSalaryResponseB(Z&my_grpc/pkg/protobuf/api/salary;salaryb\x06proto3"

var file_protobuf_api_salary_service_proto_goTypes = []any{
	(*GetSalaryRequest)(nil),  // 0: api.salary.GetSalaryRequest
	(*GetSalaryResponse)(nil), // 1: api.salary.GetSalaryResponse
}
var file_protobuf_api_salary_service_proto_depIdxs = []int32{
	0, // 0: api.salary.SalaryService.GetSalary:input_type -> api.salary.GetSalaryRequest
	1, // 1: api.salary.SalaryService.GetSalary:output_type -> api.salary.GetSalaryResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_api_salary_service_proto_init() }
func file_protobuf_api_salary_service_proto_init() {
	if File_protobuf_api_salary_service_proto != nil {
		return
	}
	file_protobuf_api_salary_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_api_salary_service_proto_rawDesc), len(file_protobuf_api_salary_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_api_salary_service_proto_goTypes,
		DependencyIndexes: file_protobuf_api_salary_service_proto_depIdxs,
	}.Build()
	File_protobuf_api_salary_service_proto = out.File
	file_protobuf_api_salary_service_proto_goTypes = nil
	file_protobuf_api_salary_service_proto_depIdxs = nil
}
