// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/salary/v2/messages.proto

package salary_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	salary "my_grpc/pkg/protobuf/api/salary"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Salary struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            uint32                    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Response      *salary.GetSalaryResponse `protobuf:"bytes,2,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Salary) Reset() {
	*x = Salary{}
	mi := &file_api_salary_v2_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Salary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Salary) ProtoMessage() {}

func (x *Salary) ProtoReflect() protoreflect.Message {
	mi := &file_api_salary_v2_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Salary.ProtoReflect.Descriptor instead.
func (*Salary) Descriptor() ([]byte, []int) {
	return file_api_salary_v2_messages_proto_rawDescGZIP(), []int{0}
}

func (x *Salary) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Salary) GetResponse() *salary.GetSalaryResponse {
	if x != nil {
		return x.Response
	}
	return nil
}

type ListSalary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSalary) Reset() {
	*x = ListSalary{}
	mi := &file_api_salary_v2_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSalary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSalary) ProtoMessage() {}

func (x *ListSalary) ProtoReflect() protoreflect.Message {
	mi := &file_api_salary_v2_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSalary.ProtoReflect.Descriptor instead.
func (*ListSalary) Descriptor() ([]byte, []int) {
	return file_api_salary_v2_messages_proto_rawDescGZIP(), []int{1}
}

var File_api_salary_v2_messages_proto protoreflect.FileDescriptor

const file_api_salary_v2_messages_proto_rawDesc = "" +
	"\n" +
	"\x1capi/salary/v2/messages.proto\x12\rapi.salary.v2\x1a\x19api/salary/messages.proto\"S\n" +
	"\x06Salary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x129\n" +
	"\bresponse\x18\x02 \x01(\v2\x1d.api.salary.GetSalaryResponseR\bresponse\"\f\n" +
	"\n" +
	"ListSalaryB\xa6\x01\n" +
	"\x11com.api.salary.v2B\rMessagesProtoP\x01Z,my_grpc/pkg/protobuf/api/salary/v2;salary_v2\xa2\x02\x03ASX\xaa\x02\rApi.Salary.V2\xca\x02\rApi\\Salary\\V2\xe2\x02\x19Api\\Salary\\V2\\GPBMetadata\xea\x02\x0fApi::Salary::V2b\x06proto3"

var (
	file_api_salary_v2_messages_proto_rawDescOnce sync.Once
	file_api_salary_v2_messages_proto_rawDescData []byte
)

func file_api_salary_v2_messages_proto_rawDescGZIP() []byte {
	file_api_salary_v2_messages_proto_rawDescOnce.Do(func() {
		file_api_salary_v2_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_salary_v2_messages_proto_rawDesc), len(file_api_salary_v2_messages_proto_rawDesc)))
	})
	return file_api_salary_v2_messages_proto_rawDescData
}

var file_api_salary_v2_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_salary_v2_messages_proto_goTypes = []any{
	(*Salary)(nil),                   // 0: api.salary.v2.Salary
	(*ListSalary)(nil),               // 1: api.salary.v2.ListSalary
	(*salary.GetSalaryResponse)(nil), // 2: api.salary.GetSalaryResponse
}
var file_api_salary_v2_messages_proto_depIdxs = []int32{
	2, // 0: api.salary.v2.Salary.response:type_name -> api.salary.GetSalaryResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_salary_v2_messages_proto_init() }
func file_api_salary_v2_messages_proto_init() {
	if File_api_salary_v2_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_salary_v2_messages_proto_rawDesc), len(file_api_salary_v2_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_salary_v2_messages_proto_goTypes,
		DependencyIndexes: file_api_salary_v2_messages_proto_depIdxs,
		MessageInfos:      file_api_salary_v2_messages_proto_msgTypes,
	}.Build()
	File_api_salary_v2_messages_proto = out.File
	file_api_salary_v2_messages_proto_goTypes = nil
	file_api_salary_v2_messages_proto_depIdxs = nil
}
