// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/salary/v2/service.proto

package salary_v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	salary "my_grpc/pkg/protobuf/api/salary"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_salary_v2_service_proto protoreflect.FileDescriptor

const file_api_salary_v2_service_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/salary/v2/service.proto\x12\rapi.salary.v2\x1a\x19api/salary/messages.proto\x1a\x1capi/salary/v2/messages.proto2\xa2\x01\n" +
	"\rSalaryService\x12L\n" +
	"\x0fGetSalaryStream\x12\x1c.api.salary.GetSalaryRequest\x1a\x15.api.salary.v2.Salary\"\x00(\x010\x01\x12C\n" +
	"\rGetListSalary\x12\x19.api.salary.v2.ListSalary\x1a\x15.api.salary.v2.Salary0\x01B\xa5\x01\n" +
	"\x11com.api.salary.v2B\fServiceProtoP\x01Z,my_grpc/pkg/protobuf/api/salary/v2;salary_v2\xa2\x02\x03ASX\xaa\x02\rApi.Salary.V2\xca\x02\rApi\\Salary\\V2\xe2\x02\x19Api\\Salary\\V2\\GPBMetadata\xea\x02\x0fApi::Salary::V2b\x06proto3"

var file_api_salary_v2_service_proto_goTypes = []any{
	(*salary.GetSalaryRequest)(nil), // 0: api.salary.GetSalaryRequest
	(*ListSalary)(nil),              // 1: api.salary.v2.ListSalary
	(*Salary)(nil),                  // 2: api.salary.v2.Salary
}
var file_api_salary_v2_service_proto_depIdxs = []int32{
	0, // 0: api.salary.v2.SalaryService.GetSalaryStream:input_type -> api.salary.GetSalaryRequest
	1, // 1: api.salary.v2.SalaryService.GetListSalary:input_type -> api.salary.v2.ListSalary
	2, // 2: api.salary.v2.SalaryService.GetSalaryStream:output_type -> api.salary.v2.Salary
	2, // 3: api.salary.v2.SalaryService.GetListSalary:output_type -> api.salary.v2.Salary
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_salary_v2_service_proto_init() }
func file_api_salary_v2_service_proto_init() {
	if File_api_salary_v2_service_proto != nil {
		return
	}
	file_api_salary_v2_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_salary_v2_service_proto_rawDesc), len(file_api_salary_v2_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_salary_v2_service_proto_goTypes,
		DependencyIndexes: file_api_salary_v2_service_proto_depIdxs,
	}.Build()
	File_api_salary_v2_service_proto = out.File
	file_api_salary_v2_service_proto_goTypes = nil
	file_api_salary_v2_service_proto_depIdxs = nil
}
