// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: protobuf/api/vacation/service.proto

package vacation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_protobuf_api_vacation_service_proto protoreflect.FileDescriptor

const file_protobuf_api_vacation_service_proto_rawDesc = "" +
	"\n" +
	"#protobuf/api/vacation/service.proto\x12\fapi.vacation\x1a$protobuf/api/vacation/messages.proto2e\n" +
	"\x0fVacationService\x12R\n" +
	"\vGetVacation\x12 .api.vacation.GetVacationRequest\x1a!.api.vacation.GetVacationResponseB#Z!my_grpc/pkg/api/vacation;vacationb\x06proto3"

var file_protobuf_api_vacation_service_proto_goTypes = []any{
	(*GetVacationRequest)(nil),  // 0: api.vacation.GetVacationRequest
	(*GetVacationResponse)(nil), // 1: api.vacation.GetVacationResponse
}
var file_protobuf_api_vacation_service_proto_depIdxs = []int32{
	0, // 0: api.vacation.VacationService.GetVacation:input_type -> api.vacation.GetVacationRequest
	1, // 1: api.vacation.VacationService.GetVacation:output_type -> api.vacation.GetVacationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protobuf_api_vacation_service_proto_init() }
func file_protobuf_api_vacation_service_proto_init() {
	if File_protobuf_api_vacation_service_proto != nil {
		return
	}
	file_protobuf_api_vacation_messages_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobuf_api_vacation_service_proto_rawDesc), len(file_protobuf_api_vacation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_api_vacation_service_proto_goTypes,
		DependencyIndexes: file_protobuf_api_vacation_service_proto_depIdxs,
	}.Build()
	File_protobuf_api_vacation_service_proto = out.File
	file_protobuf_api_vacation_service_proto_goTypes = nil
	file_protobuf_api_vacation_service_proto_depIdxs = nil
}
