// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: protobuf/api/salary/v2/messages.proto

package salary_v2

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Salary with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Salary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Salary with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in SalaryMultiError, or nil if none found.
func (m *Salary) ValidateAll() error {
	return m.validate(true)
}

func (m *Salary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	if all {
		switch v := interface{}(m.GetResponse()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, SalaryValidationError{
					field:  "Response",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, SalaryValidationError{
					field:  "Response",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResponse()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return SalaryValidationError{
				field:  "Response",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return SalaryMultiError(errors)
	}

	return nil
}

// SalaryMultiError is an error wrapping multiple validation errors returned by
// Salary.ValidateAll() if the designated constraints aren't met.
type SalaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SalaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SalaryMultiError) AllErrors() []error { return m }

// SalaryValidationError is the validation error returned by Salary.Validate if
// the designated constraints aren't met.
type SalaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SalaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SalaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SalaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SalaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SalaryValidationError) ErrorName() string { return "SalaryValidationError" }

// Error satisfies the builtin error interface
func (e SalaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSalary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SalaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SalaryValidationError{}

// Validate checks the field values on ListSalary with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ListSalary) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListSalary with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ListSalaryMultiError, or
// nil if none found.
func (m *ListSalary) ValidateAll() error {
	return m.validate(true)
}

func (m *ListSalary) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ListSalaryMultiError(errors)
	}

	return nil
}

// ListSalaryMultiError is an error wrapping multiple validation errors
// returned by ListSalary.ValidateAll() if the designated constraints aren't met.
type ListSalaryMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListSalaryMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListSalaryMultiError) AllErrors() []error { return m }

// ListSalaryValidationError is the validation error returned by
// ListSalary.Validate if the designated constraints aren't met.
type ListSalaryValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListSalaryValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListSalaryValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListSalaryValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListSalaryValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListSalaryValidationError) ErrorName() string { return "ListSalaryValidationError" }

// Error satisfies the builtin error interface
func (e ListSalaryValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListSalary.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListSalaryValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListSalaryValidationError{}
