// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: api/vacation/messages.proto

package vacation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVacationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	CountDays     int32                  `protobuf:"varint,2,opt,name=countDays,proto3" json:"countDays,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVacationRequest) Reset() {
	*x = GetVacationRequest{}
	mi := &file_api_vacation_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVacationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacationRequest) ProtoMessage() {}

func (x *GetVacationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_vacation_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacationRequest.ProtoReflect.Descriptor instead.
func (*GetVacationRequest) Descriptor() ([]byte, []int) {
	return file_api_vacation_messages_proto_rawDescGZIP(), []int{0}
}

func (x *GetVacationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetVacationRequest) GetCountDays() int32 {
	if x != nil {
		return x.CountDays
	}
	return 0
}

type GetVacationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Approve       string                 `protobuf:"bytes,1,opt,name=approve,proto3" json:"approve,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVacationResponse) Reset() {
	*x = GetVacationResponse{}
	mi := &file_api_vacation_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVacationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVacationResponse) ProtoMessage() {}

func (x *GetVacationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_vacation_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVacationResponse.ProtoReflect.Descriptor instead.
func (*GetVacationResponse) Descriptor() ([]byte, []int) {
	return file_api_vacation_messages_proto_rawDescGZIP(), []int{1}
}

func (x *GetVacationResponse) GetApprove() string {
	if x != nil {
		return x.Approve
	}
	return ""
}

var File_api_vacation_messages_proto protoreflect.FileDescriptor

const file_api_vacation_messages_proto_rawDesc = "" +
	"\n" +
	"\x1bapi/vacation/messages.proto\x12\fapi.vacation\"F\n" +
	"\x12GetVacationRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tcountDays\x18\x02 \x01(\x05R\tcountDays\"/\n" +
	"\x13GetVacationResponse\x12\x18\n" +
	"\aapprove\x18\x01 \x01(\tR\aapproveB\x95\x01\n" +
	"\x10com.api.vacationB\rMessagesProtoP\x01Z!my_grpc/pkg/api/vacation;vacation\xa2\x02\x03AVX\xaa\x02\fApi.Vacation\xca\x02\fApi\\Vacation\xe2\x02\x18Api\\Vacation\\GPBMetadata\xea\x02\rApi::Vacationb\x06proto3"

var (
	file_api_vacation_messages_proto_rawDescOnce sync.Once
	file_api_vacation_messages_proto_rawDescData []byte
)

func file_api_vacation_messages_proto_rawDescGZIP() []byte {
	file_api_vacation_messages_proto_rawDescOnce.Do(func() {
		file_api_vacation_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_vacation_messages_proto_rawDesc), len(file_api_vacation_messages_proto_rawDesc)))
	})
	return file_api_vacation_messages_proto_rawDescData
}

var file_api_vacation_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_vacation_messages_proto_goTypes = []any{
	(*GetVacationRequest)(nil),  // 0: api.vacation.GetVacationRequest
	(*GetVacationResponse)(nil), // 1: api.vacation.GetVacationResponse
}
var file_api_vacation_messages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_vacation_messages_proto_init() }
func file_api_vacation_messages_proto_init() {
	if File_api_vacation_messages_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_vacation_messages_proto_rawDesc), len(file_api_vacation_messages_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_vacation_messages_proto_goTypes,
		DependencyIndexes: file_api_vacation_messages_proto_depIdxs,
		MessageInfos:      file_api_vacation_messages_proto_msgTypes,
	}.Build()
	File_api_vacation_messages_proto = out.File
	file_api_vacation_messages_proto_goTypes = nil
	file_api_vacation_messages_proto_depIdxs = nil
}
