// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/vacation/service.proto

package vacation

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VacationService_GetVacation_FullMethodName = "/api.vacation.VacationService/GetVacation"
)

// VacationServiceClient is the client API for VacationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VacationServiceClient interface {
	GetVacation(ctx context.Context, in *GetVacationRequest, opts ...grpc.CallOption) (*GetVacationResponse, error)
}

type vacationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVacationServiceClient(cc grpc.ClientConnInterface) VacationServiceClient {
	return &vacationServiceClient{cc}
}

func (c *vacationServiceClient) GetVacation(ctx context.Context, in *GetVacationRequest, opts ...grpc.CallOption) (*GetVacationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVacationResponse)
	err := c.cc.Invoke(ctx, VacationService_GetVacation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VacationServiceServer is the server API for VacationService service.
// All implementations must embed UnimplementedVacationServiceServer
// for forward compatibility.
type VacationServiceServer interface {
	GetVacation(context.Context, *GetVacationRequest) (*GetVacationResponse, error)
	mustEmbedUnimplementedVacationServiceServer()
}

// UnimplementedVacationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVacationServiceServer struct{}

func (UnimplementedVacationServiceServer) GetVacation(context.Context, *GetVacationRequest) (*GetVacationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVacation not implemented")
}
func (UnimplementedVacationServiceServer) mustEmbedUnimplementedVacationServiceServer() {}
func (UnimplementedVacationServiceServer) testEmbeddedByValue()                         {}

// UnsafeVacationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VacationServiceServer will
// result in compilation errors.
type UnsafeVacationServiceServer interface {
	mustEmbedUnimplementedVacationServiceServer()
}

func RegisterVacationServiceServer(s grpc.ServiceRegistrar, srv VacationServiceServer) {
	// If the following call pancis, it indicates UnimplementedVacationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VacationService_ServiceDesc, srv)
}

func _VacationService_GetVacation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVacationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VacationServiceServer).GetVacation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VacationService_GetVacation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VacationServiceServer).GetVacation(ctx, req.(*GetVacationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VacationService_ServiceDesc is the grpc.ServiceDesc for VacationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VacationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.vacation.VacationService",
	HandlerType: (*VacationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVacation",
			Handler:    _VacationService_GetVacation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/vacation/service.proto",
}
